FROM tsl0922/ttyd:alpine
WORKDIR /home/worker/.newsboat
RUN mkdir /home/worker/.newsboat/cache
COPY config /home/worker/.newsboat
COPY urls /home/worker/.newsboat
RUN apk add newsboat elinks
RUN adduser -D worker
RUN chown worker:worker /home/worker/.newsboat
USER worker
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["ttyd", "-a", "newsboat"]

