FROM tsl0922/ttyd:alpine
WORKDIR /root/.newsboat
RUN mkdir /root/.newsboat/cache
COPY config /root/.newsboat
COPY urls /root/.newsboat
RUN apk add newsboat elinks
RUN adduser worker
RUN chown worker:worker /root/.newsboat
USER worker
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["ttyd", "-a", "newsboat"]

